--HS 冷冻鱼人
function c32880233.initial_effect(c)
	--spsummon
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_SPSUMMON_PROC)
	e1:SetProperty(EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_HAND)
	e1:SetCondition(c32880233.spcon)
	e1:SetOperation(c32880233.spop)
	c:RegisterEffect(e1)
	--counter
	local e2=Effect.CreateEffect(c)
	e2:SetCategory(CATEGORY_TOHAND+CATEGORY_SEARCH)
	e2:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_O)
	e2:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e2:SetCode(EVENT_SUMMON_SUCCESS)
	e2:SetTarget(c32880233.thtg)
	e2:SetOperation(c32880233.thop)
	c:RegisterEffect(e2)
	local e3=e2:Clone()
	e3:SetCode(EVENT_SPSUMMON_SUCCESS)
	c:RegisterEffect(e3)
end
function c32880233.spcon(e,c)
	if c==nil then return true end
	local tp=c:GetControler()
	return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
		and Duel.IsCanRemoveCounter(tp,1,0,0x755,2,REASON_COST)
end
function c32880233.spop(e,tp,eg,ep,ev,re,r,rp,c)
	Duel.RemoveCounter(tp,1,0,0x755,2,REASON_COST)
end
function c32880233.filter(c)
	return c:IsPosition(POS_FACEUP)
end
function c32880233.thtg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chkc then return chkc:IsLocation(LOCATION_MZONE) and chkc:IsControler(tp) and c32880233.filter(chkc) end
	if chk==0 then return Duel.IsExistingTarget(c32880233.filter,tp,LOCATION_MZONE,LOCATION_MZONE,1,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_FACEUP)
	Duel.SelectTarget(tp,c32880233.filter,tp,LOCATION_MZONE,LOCATION_MZONE,1,1,nil)
end
function c32880233.thop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=Duel.GetFirstTarget()
	local dg=Group.CreateGroup()
	local p,d=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER,CHAININFO_TARGET_PARAM)
	if tc:IsRelateToEffect(e) and tc:IsFaceup() then
	   tc:EnableCounterPermit(0x750,LOCATION_MZONE)
	   tc:AddCounter(0x750,1)
	   local e1=Effect.CreateEffect(c)
	   e1:SetType(EFFECT_TYPE_SINGLE)
	   e1:SetCode(EFFECT_CANNOT_ATTACK_ANNOUNCE)
	   tc:RegisterEffect(e1)
	   local e2=Effect.CreateEffect(c)
	   e2:SetType(EFFECT_TYPE_SINGLE)
	   e2:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
	   e2:SetProperty(EFFECT_FLAG_UNCOPYABLE)
	   e2:SetValue(1)
	   e2:SetReset(RESET_EVENT+0x1fe0000)
	   tc:RegisterEffect(e2)
	   local e3=Effect.CreateEffect(c)
	   e3:SetType(EFFECT_TYPE_SINGLE)
	   e3:SetCode(EFFECT_CANNOT_BE_XYZ_MATERIAL)
	   e3:SetProperty(EFFECT_FLAG_UNCOPYABLE)
	   e3:SetValue(1)
	   e3:SetReset(RESET_EVENT+0x1fe0000)
	   tc:RegisterEffect(e3)
	   local e4=Effect.CreateEffect(c)
	   e4:SetType(EFFECT_TYPE_SINGLE)
	   e4:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
	   e4:SetProperty(EFFECT_FLAG_UNCOPYABLE)
	   e4:SetValue(1)
	   e4:SetReset(RESET_EVENT+0x1fe0000)
	   tc:RegisterEffect(e4)
	   local e5=Effect.CreateEffect(c)
	   e5:SetType(EFFECT_TYPE_SINGLE)
	   e5:SetCode(EFFECT_CANNOT_BE_LINK_MATERIAL)
	   e5:SetProperty(EFFECT_FLAG_UNCOPYABLE)
	   e5:SetValue(1)
	   e5:SetReset(RESET_EVENT+0x1fe0000)
	   tc:RegisterEffect(e5)
	end
end